import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import tw from 'twrnc';
import api from '../api/config';
import { useRoute } from '@react-navigation/native';

const ApplicationResultScreen = () => {
  const route = useRoute();
  const { applicationId } = route.params;
  const [appData, setAppData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchStatus();
  }, []);

  const fetchStatus = async () => {
    try {
      const res = await api.get(`/api/loan/status/${applicationId}`);
      setAppData(res.data);
    } catch (err) {
      console.log('Error fetching status', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <View style={tw`flex-1 justify-center items-center bg-gray-50 dark:bg-gray-900`}><ActivityIndicator size="large" color="#2563eb" /></View>;
  if (!appData) return <Text style={tw`text-center mt-20 text-red-500 font-bold`}>Application missing.</Text>;

  return (
    <ScrollView style={tw`flex-1 bg-gray-50 dark:bg-gray-900 pt-16`} contentContainerStyle={tw`p-6 h-full pb-20`}>
      <Text style={tw`text-3xl font-black text-gray-900 dark:text-white mb-2`}>Application Details</Text>
      <Text style={tw`text-gray-500 mb-6 font-bold`}>Application ID #{applicationId}</Text>

      <View style={tw`bg-white dark:bg-gray-800 rounded-3xl p-6 shadow-lg border border-gray-100 dark:border-gray-700 mb-6`}>
        <Text style={tw`text-gray-400 font-bold text-xs uppercase tracking-widest mb-1`}>AI Recommendation</Text>
        <Text style={tw`text-2xl font-black mb-4 ${appData.final_decision === 'APPROVED' ? 'text-green-600' : appData.final_decision === 'REJECTED' ? 'text-red-500' : 'text-blue-600'}`}>
          {appData.final_decision || 'PROCESSING'}
        </Text>
        
        <Text style={tw`text-gray-400 font-bold text-xs uppercase tracking-widest mb-1`}>Fraud Risk Assessment</Text>
        <Text style={tw`text-xl font-black mb-4 text-gray-800 dark:text-white`}>
          {appData.fraud_score !== null ? `${((1 - appData.fraud_score) * 100).toFixed(1)}% Safe` : 'Pending Diagnostics'}
        </Text>

        <Text style={tw`text-gray-400 font-bold text-xs uppercase tracking-widest mb-1`}>CIBIL Score</Text>
        <Text style={tw`text-xl font-black text-gray-800 dark:text-white`}>
          {appData.cibil_score || 'N/A'}
        </Text>
      </View>

      <Text style={tw`text-xl font-bold mb-4 text-gray-800 dark:text-gray-200`}>AI Reasoning Details</Text>
      <View style={tw`bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700`}>
        {appData.ai_reasoning ? (
           <Text style={tw`text-gray-700 dark:text-gray-300 leading-6 font-medium`}>{appData.ai_reasoning}</Text>
        ) : (
           <Text style={tw`text-gray-500 italic`}>No reasoning generated by AI yet.</Text>
        )}
      </View>
    </ScrollView>
  );
};

export default ApplicationResultScreen;
